name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Install dependencies
        run: npm install
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install Sonar-Scanner
        run: npm install -g sonarqube-scanner
      - name: Run Sonar-Scanner
        run: sonar-scanner.bat -D"sonar.login=%SONAR_TOKEN%" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.projectKey=jci-bms-platform-react" -D"sonar.sources=src"
